language: node_js
node_js:
- node
after_success:
- npm run build
- "./travis-ci_auto-publish.sh"
env:
  global:
    secure: Axb5ND8AjGDtSF/eMA73/NG7Dqm85aoGlf1LhJdYv4VKViiQi61Ozw4Kae9oCvG6UMny+qPgp3PC5jE+rzNFVIz9TvjuxttCZjS8J22f8M5bRae5T4G9Tyu65Ij4RglH7LAxVb1c5Sorf7fdCq8+tOHdFRMW1E6MBARCUhONS7UVdN1do+voiQy13nNwmTPctGuALKBdvrcEnNf19U3Tap9qWO03EuwW8aFRY3EZL9vxDi47aaoTbSQZToWo1XKtyq4fWV4GxVkId+tuanWavfFVT2NkWIp6BwbsaUHG2WH56KAOphhmdR6y0uM5LqpMZgXiQnwPjSQLMppolWX70JVPUGn1W92XilodQMGdtp9MMhHnvQv5j9LQeZh1NsDHiQRVQDLD7oabQq0DschAv3+wMtrQtI807I5Zg9bx1znw8Dd+uqBBOlO53LItsrwR3WOb0dSJb5PiET5vfQJOWoqXiUacEYQxzTbQdR3KYqIR8bh/aX9R4B7mis1po31LzJHI/NAz+gLv41ysLgfhWDHQOfKzgWMnH6coyeM6ZG1YfOHOy55NlOb5PwExr2G4iYePYNckMH39vLX2s5b/xiN5UTz10Rq7Kn6Xye7erBr9sgiR0TaFQkV8OgBN/mRhnCR9s6BLyitZ73/r7GNXHSgsSIukfAKcHpda7Gmyp1I=
